var KS_FMSYS_ERRMSG_001_JS = '{0}を入力してください。';
var KS_FMSYS_ERRMSG_002_JS = '{0}を選択してください。';
var KS_FMSYS_ERRMSG_003_JS = '{0}は{1}文字以上、{2}文字以下です。';
var KS_FMSYS_ERRMSG_004_JS = '{0}は半角数字のみ入力できます。';
var KS_FMSYS_ERRMSG_005_JS = '{0}は半角英語、数字または記号のみ入力できます。';
var KS_FMSYS_ERRMSG_006_JS = '半角英語または半角数字のみ入力できます。';
var KS_FMSYS_ERRMSG_007_JS = '変更パスワードと再確認パスワードが一致しません。';
var KS_FMSYS_ERRMSG_008_JS = '全角文字のみ入力できます。';
var KS_FMSYS_ERRMSG_009_JS = '半角英語のみ入力できます。';
var KS_FMSYS_ERRMSG_010_JS = 'フォルダーがロック状態です。';
var KS_FMSYS_ERRMSG_011_JS = 'フォルダーを選択してください。';
var KS_FMSYS_ERRMSG_012_JS = 'フォルダーを一個のみ選択してください。';
var KS_FMSYS_ERRMSG_013_JS = 'フォルダーパスを確認してください。';
var KS_FMSYS_ERRMSG_014_JS = 'ロック状態のフォルダーまたはファイルが存在します。';
var KS_FMSYS_ERRMSG_015_JS = 'フォルダーのロック状態を確認してください。';
var KS_FMSYS_ERRMSG_016_JS = 'フォルダーまたはファイルを選択してください。';
var KS_FMSYS_ERRMSG_017_JS = 'フォルダーまたはファイルを一個のみ選択してください。';
var KS_FMSYS_ERRMSG_018_JS = 'フォルダーまたはファイルを選択してください。';
var KS_FMSYS_ERRMSG_019_JS = 'ファイルを選択してください。';
var KS_FMSYS_ERRMSG_020_JS = 'フォルダー名が長すぎます。';
var KS_FMSYS_ERRMSG_021_JS = '以下の特殊文字は使用できません。（\\/:*?"<>|%&#\'=~^!$@+;）';
var KS_FMSYS_ERRMSG_022_JS = 'ファイルを添付してください。';
var KS_FMSYS_ERRMSG_023_JS = '同じファイルが添付されています。';
var KS_FMSYS_ERRMSG_024_JS = 'ロック状態のフォルダーまたはファイルは削除できません。';
var KS_FMSYS_ERRMSG_025_JS = 'フォルダーは削除できません。';
var KS_FMSYS_ERRMSG_026_JS = 'ロック状態のファイルは削除できません。';
var KS_FMSYS_ERRMSG_027_JS = '先頭文字が "."（ドット）はファイル名やフォルダー名として指定できません。';
var KS_FMSYS_ERRMSG_028_JS = 'システム予約語はファイル名やフォルダー名として指定できません。';
var KS_FMSYS_ERRMSG_029_JS = 'ルートフォルダー配下にはファイルのアップロードはできません。';

var KS_FMSYS_ERRMSG_030_JS = '英文字のみ入力できます。';
var KS_FMSYS_ERRMSG_031_JS = '全角日本語だけ入力してください。';
var KS_FMSYS_ERRMSG_032_JS = '正しい日付を入力してください。';
	
var KS_FMSYS_INFMSG_001_JS = 'ログアウトします。よろしいですか？';
var KS_FMSYS_INFMSG_002_JS = '最新ファイルをダウンロードする場合、ロックされます。よろしいですか。';
var KS_FMSYS_INFMSG_003_JS = '削除しますか?';
var KS_FMSYS_INFMSG_004_JS = '次のファイルをダウンロードします。よろしいでしょうか?\n\n';